"""add_ban_banco_ban_cuenta

Revision ID: 23f95a53939d
Revises: 8499f1948110
Create Date: 2026-06-06 17:32:53.449135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23f95a53939d'
down_revision: Union[str, None] = '8499f1948110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_banco',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ban_cuenta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('banco_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('moneda_id', sa.UUID(), nullable=True),
    sa.Column('cuenta_contable_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo IN ('CORRIENTE','AHORRO')", name='chk_ban_cuenta_tipo'),
    sa.ForeignKeyConstraint(['banco_id'], ['ban_banco.id'], ),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cnt_cuenta.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['adm_moneda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ban_cuenta')
    op.drop_table('ban_banco')
    # ### end Alembic commands ###
