"""add_fac_resolucion

Revision ID: 3a11a32829f8
Revises: 25d245535a4d
Create Date: 2026-06-06 17:57:25.816703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a11a32829f8'
down_revision: Union[str, None] = '25d245535a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fac_resolucion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('numero_resolucion', sa.String(length=50), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=True),
    sa.Column('rango_desde', sa.Integer(), nullable=False),
    sa.Column('rango_hasta', sa.Integer(), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo IN ('FACTURA_VENTA','NOTA_CREDITO','NOTA_DEBITO')", name='chk_resolucion_tipo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefijo', 'tipo', name='uq_resolucion_prefijo_tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fac_resolucion')
    # ### end Alembic commands ###
