"""add_condicion_pago_tarifa_iva_retencion

Revision ID: 8499f1948110
Revises: c0d1e2f3a4b5
Create Date: 2026-06-06 16:04:30.126480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8499f1948110'
down_revision: Union[str, None] = 'c0d1e2f3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_condicion_pago',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dias_vencimiento', sa.SmallInteger(), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('adm_retencion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('base_minima', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cuenta_compras_id', sa.UUID(), nullable=True),
    sa.Column('cuenta_ventas_id', sa.UUID(), nullable=True),
    sa.Column('aplica_compra', sa.Boolean(), nullable=False),
    sa.Column('aplica_venta', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo IN ('RETEFUENTE','RETEICA','RETEIVA')", name='chk_retencion_tipo'),
    sa.ForeignKeyConstraint(['cuenta_compras_id'], ['cnt_cuenta.id'], ),
    sa.ForeignKeyConstraint(['cuenta_ventas_id'], ['cnt_cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_tarifa_iva',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cuenta_iva_ventas_id', sa.UUID(), nullable=True),
    sa.Column('cuenta_iva_compras_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo IN ('GRAVADO','EXENTO','EXCLUIDO')", name='chk_tarifa_iva_tipo'),
    sa.ForeignKeyConstraint(['cuenta_iva_compras_id'], ['cnt_cuenta.id'], ),
    sa.ForeignKeyConstraint(['cuenta_iva_ventas_id'], ['cnt_cuenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adm_tarifa_iva')
    op.drop_table('adm_retencion')
    op.drop_table('adm_condicion_pago')
    # ### end Alembic commands ###
