"""fase_0_fundacion

Revision ID: c30f634ace27
Revises: 
Create Date: 2026-06-02 18:21:42.592517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c30f634ace27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_concepto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('iva_tipo', sa.String(length=20), nullable=False),
    sa.Column('iva_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cuenta_iva_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('adm_configuracion',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('adm_modulo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('adm_moneda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('simbolo', sa.String(length=10), nullable=False),
    sa.Column('decimales', sa.SmallInteger(), nullable=False),
    sa.Column('es_funcional', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('adm_rol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('adm_tipo_documento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cnt_periodo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('mes', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_por', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("estado IN ('abierto','cerrado','bloqueado')", name='chk_estado_periodo'),
    sa.CheckConstraint('fecha_cierre >= fecha_inicio', name='chk_fechas_periodo'),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='chk_mes_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', name='uq_periodo_anio_mes')
    )
    op.create_table('adm_concepto_cuenta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concepto_id', sa.UUID(), nullable=False),
    sa.Column('cuenta_codigo', sa.String(length=20), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['adm_concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_concepto_retencion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concepto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('base_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('aplica_compra', sa.Boolean(), nullable=False),
    sa.Column('aplica_venta', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['adm_concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_consecutivo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento_id', sa.UUID(), nullable=False),
    sa.Column('prefijo', sa.String(length=20), nullable=True),
    sa.Column('numero_actual', sa.BigInteger(), nullable=False),
    sa.Column('numero_inicio', sa.BigInteger(), nullable=False),
    sa.Column('longitud_minima', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['adm_tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_documento_id')
    )
    op.create_table('adm_empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('digito_verif', sa.String(length=1), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('regimen', sa.String(length=50), nullable=True),
    sa.Column('responsable_iva', sa.Boolean(), nullable=False),
    sa.Column('moneda_funcional_id', sa.UUID(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['moneda_funcional_id'], ['adm_moneda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('adm_permiso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('modulo_id', sa.UUID(), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=False),
    sa.Column('puede_crear', sa.Boolean(), nullable=False),
    sa.Column('puede_editar', sa.Boolean(), nullable=False),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=False),
    sa.Column('puede_imprimir', sa.Boolean(), nullable=False),
    sa.Column('puede_autorizar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['adm_modulo.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['adm_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'modulo_id', name='uq_permiso_rol_modulo')
    )
    op.create_table('adm_trm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moneda_origen_id', sa.UUID(), nullable=False),
    sa.Column('moneda_destino_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tasa', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.CheckConstraint('moneda_origen_id <> moneda_destino_id', name='chk_monedas_distintas'),
    sa.ForeignKeyConstraint(['moneda_destino_id'], ['adm_moneda.id'], ),
    sa.ForeignKeyConstraint(['moneda_origen_id'], ['adm_moneda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moneda_origen_id', 'moneda_destino_id', 'fecha', name='uq_trm_moneda_fecha')
    )
    op.create_table('adm_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modificado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['adm_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cnt_periodo_reapertura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('autorizado_por', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['cnt_periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_password_reset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['adm_usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('adm_sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['adm_usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adm_sesion')
    op.drop_table('adm_password_reset')
    op.drop_table('cnt_periodo_reapertura')
    op.drop_table('adm_usuario')
    op.drop_table('adm_trm')
    op.drop_table('adm_permiso')
    op.drop_table('adm_empresa')
    op.drop_table('adm_consecutivo')
    op.drop_table('adm_concepto_retencion')
    op.drop_table('adm_concepto_cuenta')
    op.drop_table('cnt_periodo')
    op.drop_table('adm_tipo_documento')
    op.drop_table('adm_rol')
    op.drop_table('adm_moneda')
    op.drop_table('adm_modulo')
    op.drop_table('adm_configuracion')
    op.drop_table('adm_concepto')
    op.drop_table('adm_auditoria')
    # ### end Alembic commands ###
